import React, { useState } from 'react';
import type { GeneratedGlyph } from '../utils/geminiApi';
import { HelpCircle, Edit3, RefreshCw, X, ShieldAlert } from 'lucide-react';

interface GlyphGridProps {
  characters: { char: string; code: number; name: string; blockId: string }[];
  generatedGlyphs: Record<number, GeneratedGlyph>;
  generatingCodes: number[];
  failedCodes: number[];
  onRegenerateGlyph: (code: number) => void;
  onUpdateGlyphPath: (code: number, path: string, width: number) => void;
}

export const GlyphGrid: React.FC<GlyphGridProps> = ({
  characters,
  generatedGlyphs,
  generatingCodes,
  failedCodes,
  onRegenerateGlyph,
  onUpdateGlyphPath,
}) => {
  const [selectedCode, setSelectedCode] = useState<number | null>(null);
  const [editingPath, setEditingPath] = useState('');
  const [editingWidth, setEditingWidth] = useState(600);

  const inspectedGlyph = selectedCode !== null ? generatedGlyphs[selectedCode] : null;
  const inspectedCharMeta = selectedCode !== null ? characters.find(c => c.code === selectedCode) : null;

  const handleInspect = (code: number) => {
    const glyph = generatedGlyphs[code];
    if (glyph) {
      setSelectedCode(code);
      setEditingPath(glyph.path);
      setEditingWidth(glyph.width);
    }
  };

  const handleSavePathEdit = () => {
    if (selectedCode !== null) {
      onUpdateGlyphPath(selectedCode, editingPath, editingWidth);
      setSelectedCode(null);
    }
  };

  return (
    <div className="glass-panel p-5 flex flex-col gap-4 flex-1">
      <div className="flex justify-between items-center border-b border-white/5 pb-3">
        <div>
          <h3 className="text-md font-semibold text-slate-200">Character Synthesis Matrix</h3>
          <p className="text-xs text-slate-400">Preview vector outlines as they are generated by AI</p>
        </div>
        <div className="flex gap-4 text-xs font-mono">
          <div className="flex items-center gap-1.5 text-slate-400">
            <div className="w-2 h-2 rounded-full bg-white/20 border border-white/10" />
            <span>Pending</span>
          </div>
          <div className="flex items-center gap-1.5 text-teal-400">
            <div className="w-2 h-2 rounded-full bg-teal-500 animate-ping" />
            <span>AI Drawing</span>
          </div>
          <div className="flex items-center gap-1.5 text-indigo-400">
            <div className="w-2 h-2 rounded-full bg-indigo-500" />
            <span>Completed</span>
          </div>
        </div>
      </div>

      {characters.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-16 text-slate-400 gap-3 border border-dashed border-white/5 rounded-xl bg-black/10">
          <HelpCircle size={40} className="text-slate-600 floating" />
          <p className="text-sm">No Unicode blocks selected.</p>
          <p className="text-xs text-slate-500">Pick a Unicode range from the sidebar to activate the grid.</p>
        </div>
      ) : (
        <div className="grid grid-cols-4 sm:grid-cols-6 md:grid-cols-8 lg:grid-cols-10 gap-2.5 max-h-[480px] overflow-y-auto pr-1">
          {characters.map((c) => {
            const glyph = generatedGlyphs[c.code];
            const isGenerating = generatingCodes.includes(c.code);
            const isFailed = failedCodes.includes(c.code);
            const isDone = !!glyph;

            let cardClass = 'border-white/5 bg-black/20 text-slate-500 border-dashed';
            if (isGenerating) cardClass = 'border-teal-500/40 bg-teal-500/5 text-teal-300 pulse-glow';
            else if (isFailed) cardClass = 'border-rose-500/30 bg-rose-500/5 text-rose-400';
            else if (isDone) cardClass = 'border-indigo-500/20 bg-indigo-500/2 hover:border-indigo-500/50 hover:bg-indigo-500/5 text-slate-200 cursor-pointer';

            return (
              <div
                key={c.code}
                onClick={() => isDone && handleInspect(c.code)}
                className={`relative aspect-square flex flex-col items-center justify-center rounded-xl border transition-all select-none group ${cardClass}`}
              >
                {/* Micro scanline during AI drawing */}
                {isGenerating && <div className="scanline" />}

                {isDone ? (
                  <div className="w-full h-full flex flex-col items-center justify-center p-2">
                    <svg viewBox="0 0 1000 1000" className="w-10 h-10 text-white fill-current transform scale-y-[-1] origin-center mt-1">
                      {/* Font coords have Y pointing up. SVG renders normal with Y-axis flipped back */}
                      <path d={glyph.path} />
                    </svg>
                    <span className="text-[10px] text-indigo-400 font-mono mt-1 opacity-70 group-hover:opacity-100 transition-opacity">
                      {c.char}
                    </span>
                  </div>
                ) : isGenerating ? (
                  <div className="flex flex-col items-center gap-1">
                    <RefreshCw className="animate-spin text-teal-400" size={16} />
                    <span className="text-[9px] font-mono tracking-wider font-semibold text-teal-400/80">AI</span>
                  </div>
                ) : isFailed ? (
                  <div className="flex flex-col items-center gap-1 p-1 text-center">
                    <ShieldAlert size={16} className="text-rose-400" />
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        onRegenerateGlyph(c.code);
                      }}
                      className="text-[8px] bg-rose-500/20 hover:bg-rose-500/40 text-rose-300 font-bold px-1 py-0.5 rounded transition-colors"
                    >
                      Retry
                    </button>
                  </div>
                ) : (
                  <div className="flex flex-col items-center gap-0.5">
                    <span className="text-lg font-light text-slate-600">{c.char}</span>
                    <span className="text-[8px] font-mono text-slate-700">U+{c.code.toString(16).toUpperCase().padStart(4, '0')}</span>
                  </div>
                )}

                {/* Edit hover overlay */}
                {isDone && (
                  <div className="absolute inset-0 bg-indigo-900/80 backdrop-blur-xs flex items-center justify-center opacity-0 group-hover:opacity-100 rounded-xl transition-all duration-200">
                    <Edit3 size={14} className="text-white" />
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}

      {/* INSPECTOR & PATH EDITOR MODAL */}
      {inspectedGlyph && inspectedCharMeta && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-xs p-4">
          <div className="glass-panel-glow w-full max-w-2xl p-6 relative overflow-hidden flex flex-col md:flex-row gap-6">
            <button
              onClick={() => setSelectedCode(null)}
              className="absolute top-4 right-4 text-slate-400 hover:text-white p-1 rounded-full border border-white/5 bg-white/2 hover:bg-white/5 transition-colors"
            >
              <X size={18} />
            </button>

            {/* Left side preview */}
            <div className="flex flex-col items-center gap-4 bg-black/40 border border-white/5 p-5 rounded-2xl md:w-1/2">
              <span className="text-xs text-slate-400 uppercase tracking-wider font-semibold font-display">
                Vector Canvas Preview
              </span>
              <div className="relative aspect-square w-full max-w-[200px] border border-white/10 rounded-xl bg-[#0f0f12] flex items-center justify-center shadow-inner overflow-hidden p-4">
                {/* Guideline guides visual inside inspector */}
                <div className="absolute inset-0 pointer-events-none opacity-20 flex flex-col justify-between">
                  <div className="w-full border-b border-rose-500" style={{ top: '20%', position: 'absolute' }} />
                  <div className="w-full border-b border-amber-500" style={{ top: '45%', position: 'absolute' }} />
                  <div className="w-full border-b border-emerald-500" style={{ top: '80%', position: 'absolute' }} />
                  <div className="w-full border-b border-blue-500" style={{ top: '95%', position: 'absolute' }} />
                </div>
                
                <svg viewBox="0 0 1000 1000" className="w-full h-full text-indigo-400 fill-current transform scale-y-[-1] origin-center">
                  <path d={editingPath} />
                </svg>
              </div>

              <div className="flex gap-2 w-full justify-center">
                <button
                  onClick={() => {
                    onRegenerateGlyph(inspectedCharMeta.code);
                    setSelectedCode(null);
                  }}
                  className="btn-secondary text-xs py-2 px-3 flex items-center gap-1.5"
                >
                  <RefreshCw size={12} />
                  Regenerate Glyph
                </button>
              </div>
            </div>

            {/* Right side SVG inspector/editor */}
            <div className="flex flex-col gap-4 flex-1 md:w-1/2 justify-between">
              <div className="flex flex-col gap-2">
                <h3 className="text-lg font-bold text-slate-200 flex items-center gap-2">
                  <span>Glyph Editor: '{inspectedCharMeta.char}'</span>
                  <span className="text-xs bg-indigo-500/10 text-indigo-400 px-2 py-0.5 rounded border border-indigo-500/20 font-mono font-medium">
                    U+{inspectedCharMeta.code.toString(16).toUpperCase().padStart(4, '0')}
                  </span>
                </h3>
                <p className="text-xs text-slate-400">{inspectedCharMeta.name}</p>
              </div>

              {/* Path String Editor */}
              <div className="flex flex-col gap-2.5">
                <div className="flex flex-col gap-1">
                  <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">
                    SVG Coordinate Path (d string)
                  </label>
                  <textarea
                    rows={4}
                    value={editingPath}
                    onChange={(e) => setEditingPath(e.target.value)}
                    className="w-full text-input font-mono text-xs bg-[#0d0d11] resize-none leading-relaxed"
                  />
                </div>

                {/* Advance Width adjust slider */}
                <div className="flex flex-col gap-1">
                  <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider flex justify-between">
                    <span>Advance Width</span>
                    <span className="font-mono text-indigo-400 font-semibold">{editingWidth} em</span>
                  </label>
                  <div className="flex gap-3 items-center">
                    <input
                      type="range"
                      min="150"
                      max="1200"
                      value={editingWidth}
                      onChange={(e) => setEditingWidth(parseInt(e.target.value))}
                      className="flex-1 accent-indigo-500 cursor-ew-resize h-1 bg-white/10 rounded-lg appearance-none"
                    />
                  </div>
                </div>
              </div>

              {/* Actions bar */}
              <div className="flex gap-2 border-t border-white/5 pt-4 justify-end">
                <button
                  onClick={() => setSelectedCode(null)}
                  className="btn-secondary py-2 px-4 text-xs"
                >
                  Discard
                </button>
                <button
                  onClick={handleSavePathEdit}
                  className="btn-primary py-2 px-5 text-xs font-bold"
                >
                  Apply Edits
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
